data_paths:
  X_train_path: data/processed/X_train.csv
  save_model_path: deployment/rforest_model.pkl
  y_train_path: data/processed/y_train.csv
model_params:
  class_weight: balanced
  criterion: gini
  max_depth: 8
  max_features: sqrt
  min_samples_leaf: 2
  min_samples_split: 5
  n_estimators: 300
  n_jobs: -1
  random_state: 42
